# Generated by Django 4.2.1 on 2023-05-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dat_banco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('cpf', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('saldo', models.FloatField()),
                ('senha', models.TextField()),
                ('nascimento', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
